### ISSUE TITLE
CreateAIprofile failing with 504 Gateway Timeout

### ISSUE THREAD

**Issue by nileshamritphale** [OracleSiebel/ConfiguringSiebel#86] opened 2020-07-09 10:08 UTC
We are setting up siebel and have successed in running all scripts however facing issue with CreateAIprofile step which is failing with 504 gateway timeout error. I m just 2 steps away in setting up this automation and need help in solving this issue . I have tried GET for AI profiles and it is giving result meaning connectivity is not an issue. Any pointers??

**Comment by OracleSiebel** [comment] 2020-07-09 10:50
I think the issue is most likely that the JSON content for creating the SAI profile has changed over the last two years. I would resolve this by creating the SAI profile manually via SMC, observing the JSON sent using the 'Network' tab in the browser developer tools, and then adjusting the JSON in the automate-architecture/smc folder.

**Comment by nileshamritphale** [comment] 2020-07-09 11:07
I did a GET on the existing profiles created a copy of the same and
submitted the request still the same. Do you think the issue is with JSON
only or it is something else?

**Comment by OracleSiebel** [comment] 2020-07-09 12:30
I don't understand what you mean. I suspect the main issue is that minConnections is no longer a parameter and you need to remove this line:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/manage/scripts/automate-architecture/smc/createSAIProfile#L54

**Comment by OracleSiebel** [comment] 2021-03-08 10:40
Closing this. The latest build content takes this issue into account.

**Closed by OracleSiebel** 2021-03-08 10:40 UTC
